export const VIDEO_CREATE_REQUEST = "VIDEO_CREATE_REQUEST"
export const VIDEO_CREATE_SUCCESS = "VIDEO_CREATE_SUCCESS"
export const VIDEO_CREATE_FAIL = "VIDEO_CREATE_FAIL"
export const VIDEO_CREATE_RESET = "VIDEO_CREATE_RESET"

export const VIDEO_ALL_REQUEST = "VIDEO_ALL_REQUEST"
export const VIDEO_ALL_SUCCESS = "VIDEO_ALL_SUCCESS"
export const VIDEO_ALL_FAIL = "VIDEO_ALL_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS"